In [1]:
import pandas as pd
import json

In [6]:
## 從rest api 的方向抓
## https://cloud.culture.tw/frontsite/trans/SearchShowAction.do?method=doFindTypeJ&category=all
## 以category all 做選擇 拉取所有活動

local_path ="C:/Users/USER/Desktop/python_work"


    
df = pd.read_json(local_path + "/" + "all_category.json")



df.replace('^\s+', '', regex=True, inplace=True) #front
df.replace('\s+$', '', regex=True, inplace=True) #end
show_df= df[['version', 'UID','title','category','discountInfo','masterUnit','comment','startDate','endDate','hitRate']]
df['masterUnit'] = df['masterUnit'].astype(str)
display(show_df)

,version,UID,title,category,discountInfo,masterUnit,comment,startDate,endDate,hitRate
0,1.4,5aa90765c6355e63fc0cf750,週末蚊子電影院-Cars 2：世界大賽,16,,[],,2112/01/29,2112/01/29,0
1,1.4,5b3dd544aaa378d7ca9a2e9a,科博館《古代人說故事》南屯山仔腳遺址出土的鐵刀首亮相!,6,,[國立自然科學博物館],,2021/10/19,2028/12/31,1724
2,1.4,5b3dd544aaa378d7ca9a2e9a,科博館《古代人說故事》南屯山仔腳遺址出土的鐵刀首亮相!,4,,[國立自然科學博物館],,2021/10/19,2028/12/31,1724
3,1.4,5c7e1bcdaaa375d860933d3a,曾侯乙編鐘「重返」科博館 小編鐘與VR相伴共推科學教育,6,,[國立自然科學博物館],,2019/03/05,2024/03/05,1771
4,1.4,5c7e1bcdaaa375d860933d3a,曾侯乙編鐘「重返」科博館 小編鐘與VR相伴共推科學教育,4,,[國立自然科學博物館],,2019/03/05,2024/03/05,1771
...,...,...,...,...,...,...,...,...,...,...
3674,1.4,616c747cd083a38f6c36c801,老屋。花園 巡迴演唱會,1,,[山狗大樂團],,2021/10/30,2021/10/30,0
3675,1.4,616c747cd083a38f6c36c802,老屋。花園 巡迴演唱會,1,,[山狗大樂團],,2021/10/31,2021/10/31,0
3676,1.4,616d191eaaa3465eb167c948,teamLab未來遊樂園&與花共生的動物們,6,,[teamLab Kids 、 聯合數位文創],,2021/10/08,2022/02/28,0
3677,1.4,616d1bb6aaa3465eb167c949,2021鶯歌藝術季,6,,[新北市政府、新北市政府文化局、新北市立鶯歌陶瓷博物館、新北市美術館],,2021/10/09,2021/12/26,0
3678,1.4,616d1bb6aaa3465eb167c949,2021鶯歌藝術季,4,,[新北市政府、新北市政府文化局、新北市立鶯歌陶瓷博物館、新北市美術館],,2021/10/09,2021/12/26,0

In [7]:
import pymysql
from sqlalchemy import create_engine
# Open database connection
# conn = pymysql.connect(host='127.0.0.1', port=3306, user='testadmin', passwd='testadmin', db='test', charset='utf8')
conn  =create_engine('mysql+pymysql://testadmin:testadmin@localhost:3306/test?charset=utf8mb4')


show_df.to_sql(name='all_category', con=conn, if_exists = 'replace', index=False)

ProgrammingError: (pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '), '', '2112/01/29', '2112/01/29', 0),(1.4e0, '5b3dd544aaa378d7ca9a2e9a', '科å\x8d' at line 1")
[SQL: INSERT INTO all_category (version, `UID`, title, category, `discountInfo`, `masterUnit`, comment, `startDate`, `endDate`, `hitRate`) VALUES (%(version)s, %(UID)s, %(title)s, %(category)s, %(discountInfo)s, %(masterUnit)s, %(comment)s, %(startDate)s, %(endDate)s, %(hitRate)s)]
[parameters: ({'version': 1.4, 'UID': '5aa90765c6355e63fc0cf750', 'title': '週末蚊子電影院-Cars 2：世界大賽', 'category': 16, 'discountInfo': '', 'masterUnit': [], 'comment': '', 'startDate': '2112/01/29', 'endDate': '2112/01/29', 'hitRate': 0}, {'version': 1.4, 'UID': '5b3dd544aaa378d7ca9a2e9a', 'title': '科博館《古代人說故事》南屯山仔腳遺址出土的鐵刀首亮相!', 'category': 6, 'discountInfo': '', 'masterUnit': ['國立自然科學博物館'], 'comment': '', 'startDate': '2021/10/19', 'endDate': '2028/12/31', 'hitRate': 1724}, {'version': 1.4, 'UID': '5b3dd544aaa378d7ca9a2e9a', 'title': '科博館《古代人說故事》南屯山仔腳遺址出土的鐵刀首亮相!', 'category': 4, 'discountInfo': '', 'masterUnit': ['國立自然科學博物館'], 'comment': '', 'startDate': '2021/10/19', 'endDate': '2028/12/31', 'hitRate': 1724}, {'version': 1.4, 'UID': '5c7e1bcdaaa375d860933d3a', 'title': '曾侯乙編鐘「重返」科博館  小編鐘與VR相伴共推科學教育', 'category': 6, 'discountInfo': '', 'masterUnit': ['國立自然科學博物館'], 'comment': '', 'startDate': '2019/03/05', 'endDate': '2024/03/05', 'hitRate': 1771}, {'version': 1.4, 'UID': '5c7e1bcdaaa375d860933d3a', 'title': '曾侯乙編鐘「重返」科博館  小編鐘與VR相伴共推科學教育', 'category': 4, 'discountInfo': '', 'masterUnit': ['國立自然科學博物館'], 'comment': '', 'startDate': '2019/03/05', 'endDate': '2024/03/05', 'hitRate': 1771}, {'version': 1.4, 'UID': '5c9a1560d083a30290d1b36f', 'title': '傳藝工坊－工藝師駐園資訊', 'category': 3, 'discountInfo': '', 'masterUnit': ['國立傳統藝術中心'], 'comment': '', 'startDate': '2021/02/15', 'endDate': '2021/12/15', 'hitRate': 1655}, {'version': 1.4, 'UID': '5cd25532aaa3f054c2cc6bad', 'title': '魔幻琺瑯/七宝烧體驗課程', 'category': 19, 'discountInfo': '不預收費用，上課繳費', 'masterUnit': ['築好玩藝'], 'comment': '因空間有限，怕線上報名超額超收，※限額課程在收到您的報名資料後無論有沒有在限額內築好玩藝一定會再一天內發Mail與您聯絡（若一天內沒收到mail請查一下您信箱垃圾桶），※限額課程若報名在名額外才會專人電話通知....築好玩藝團隊歡迎您.....感謝！！', 'startDate': '2021/10/23', 'endDate': '2029/12/30', 'hitRate': 1889}, {'version': 1.4, 'UID': '5cd25532aaa3f054c2cc6bad', 'title': '魔幻琺瑯/七宝烧體驗課程', 'category': 4, 'discountInfo': '不預收費用，上課繳費', 'masterUnit': ['築好玩藝'], 'comment': '因空間有限，怕線上報名超額超收，※限額課程在收到您的報名資料後無論有沒有在限額內築好玩藝一定會再一天內發Mail與您聯絡（若一天內沒收到mail請查一下您信箱垃圾桶），※限額課程若報名在名額外才會專人電話通知....築好玩藝團隊歡迎您.....感謝！！', 'startDate': '2021/10/23', 'endDate': '2029/12/30', 'hitRate': 1889}  ... displaying 10 of 3679 total bound parameter sets ...  {'version': 1.4, 'UID': '616d1bb6aaa3465eb167c949', 'title': '2021鶯歌藝術季', 'category': 6, 'discountInfo': '', 'masterUnit': ['新北市政府、新北市政府文化局、新北市立鶯歌陶瓷博物館、新北市美術館'], 'comment': '', 'startDate': '2021/10/09', 'endDate': '2021/12/26', 'hitRate': 0}, {'version': 1.4, 'UID': '616d1bb6aaa3465eb167c949', 'title': '2021鶯歌藝術季', 'category': 4, 'discountInfo': '', 'masterUnit': ['新北市政府、新北市政府文化局、新北市立鶯歌陶瓷博物館、新北市美術館'], 'comment': '', 'startDate': '2021/10/09', 'endDate': '2021/12/26', 'hitRate': 0})]
(Background on this error at: https://sqlalche.me/e/14/f405)